version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
      - "50051:50051" # gRPC port
    depends_on:
      - db
